### ISSUE TITLE
Character limit[Idea]

### ISSUE THREAD

**Issue by Huelz** [micahlt/modchat#10]
As some us have seen earlier today, spammers have used large amounts of characters when spamming, which goes over other messages. To prevent this, we could have a character limit, possibly around 300 characters. As this wont prevent spamming, this can help reduce how many characters are used.

**Comment by Nambaseking01** [comment]
Perhaps a max of 250?

**Comment by micahlt** [comment]
This was first added in commit 1cf47372e6bab5a909ccfeec3277c815c73fcc4c but the character limit is currently 200.
