### ISSUE TITLE
[Bug] A word isn't included as a bad word

### ISSUE THREAD

**Issue by Nambaseking01** [micahlt/modchat#11]
**Describe the bug**
Fr**k doesn't get censored - I saw a user using it on the "def" room, you should probably fix that. I don't really understand yet how the censoring thing works, so I decided not to commit as I might make some mistake that bugs out Modchat.

**Comment by Huelz** [comment]
Other words, like F*ck, sh*t and others work too. Another issue is adding underscored between letters

**Comment by Nambaseking01** [comment]
Yeah, that gives an easy workaround. I'm working on an issue for that rn too..

**Comment by micahlt** [comment]
@Nambaseking01 Freak is not a curse word.  @Huelz It's just like Scratch- there are going to be workarounds.

**Comment by Nambaseking01** [comment]
No, I'm not talking about freak, I'm talking about fri*k.

**Comment by micahlt** [comment]
@Nambaseking01 You mean frick?  That's just a weird version of freak, and it's not a curse word either.

**Comment by Nambaseking01** [comment]
Yes, but I remember Paddle censored someone who said it (I remember exactly who, but no naming and shaming). I'm pretty sure it was fri*k.

**Comment by micahlt** [comment]
Hmmm... we'll leave it how it is right now.  If it becomes an issue I'll add it to the blacklist.
