### ISSUE TITLE
[Bug] Impersonation

### ISSUE THREAD

**Issue by Nambaseking01** [micahlt/modchat#12]
**Describe the bug**
You probably already know this, but people can pretend to be others user right now. I saw a user even impersonating @griffpatch and me, but luckily only I was there so I knew the person was just doing it for a good laugh.  Seriously though, could you look into this?

**Additional context**
You could mark this high-prio, as impersonation is a huge problem on Scratch as well.

**Comment by micahlt** [comment]
@Nambaseking01 Fixed this in commit a8a6d1b2e8e40ec2a7a067679b3e816395c8a109.
