### ISSUE TITLE
[Idea] Report button

### ISSUE THREAD

**Issue by Nambaseking01** [micahlt/modchat#13]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I can't help out with stopping people breaking the rules of Modchat.

**Describe the solution you'd like**
You could make a Report button with which people can report people that break the rules (e.g. impersonation or spamming). Additionally, there could be a textbox in which one can clearly explain how the post offended them. And then, you could come and there would be moderator logs of the user, the user who reported the comment, then the comment itself, and the sent textbox. 

Additionally, way later when it's actually capable, you could be able to invite new moderators that you trust and they could apply for it in some way, 

**Additional context**
This might be very hard to code, but please consider it for in the future. I understand that saving that much data can go wrong sometimes in JS.

**Comment by ConvexPolygon** [comment]
I would like to be a mod :)

**Comment by micahlt** [comment]
@ConvexPolygon Hey, can you help design a reporting system?  I'm kind of overwhelmed with feature requests right now.

**Comment by Nambaseking01** [comment]
Micah, sorry for all the feature requests, you can do one at a time.. I just like to spurt out my ideas, I get way too much

**Comment by micahlt** [comment]
@Nambaseking01 No problem, just asking for some help.  :D

**Comment by ConvexPolygon** [comment]
> @ConvexPolygon Hey, can you help design a reporting system? I'm kind of overwhelmed with feature requests right now.

Ok. Do you want it to instantly hide it and lengthen cooldown? BTW, I would like some way to test ModChat. My heroku account is support@jtechnologies.xyz

**Comment by micahlt** [comment]
@ConvexPolygon I'd rather have the system work like this: 

1. User reports a message
2. Message contents are sent to the server via Socket.io
3. Socket.io server sends a notification (see my in-progress notification API) to every admin on the mods list
4. Admin has the option to ban the user or mute them

Do you think you can make a beta of that?

**Comment by ConvexPolygon** [comment]
Maybe. Admin or Moderator?

**Comment by ConvexPolygon** [comment]
Can ban?

**Comment by micahlt** [comment]
@ConvexPolygon Ah, they're the same thing.  In the code (`index.js`) I think the list is called mods.

**Comment by ConvexPolygon** [comment]
got it. I'll do what I can before my marathon of new singles :)
11:45, 12:00, 12:15.

**Comment by micahlt** [comment]
Yep!  I'm planning on listening.  :D

**Comment by ConvexPolygon** [comment]
Cool :)

**Comment by micahlt** [comment]
@VelocityDesign @Nambaseking01 This was added in 7cac893158ad071d20684d93ccf7d2e3ce0f9a28.
