### ISSUE TITLE
Need assistance!

### ISSUE THREAD

**Issue by micahlt** [micahlt/modchat#14]
Starting Modchat was a huge decision that I was clearly not ready for.  I'm not a backend developer, but I tried to use Node.js anyway.  I'm not a framework user, but I decided to use Socket.io anyway.

The point is, I'm at a standstill.  I need more developers working on this project with me.  I've turned off the dyno on Heroku because of spam and security issues.  My code is bloated and wacked up.

I need developers with experience in:
- Encryption
- Authenication
- Security
- Moderation
- DOM Manipulation
- Node and/or Socket.io

I really don't want this project to die, but I can't feasibly continue by myself.
If you're interested, drop a comment.

**Comment by Skyclo** [comment]
I would be willing to help with back-end development. I am experienced with Node, and DOM Manipulation. However, I would not be able to take up the project right now, but I would be willing to contribute where I can.

**Comment by Nambaseking01** [comment]
You might want to pin this issue so many more can see it. Additionally, you could fix the grammatical mistake in that label text, it's triggering my OCD... :P

**Comment by ConvexPolygon** [comment]
You got me for encryption and cybersecurity! I'm certified in Cryptography and Cyber Security by ProgrammingHub.io Pro
I can also do moderation.

**Comment by micahlt** [comment]
@Skyclo Really appreciate it!  I understand you're busy with Ideoxan, though.  I'll be sure to let you know if I really need any major backend help.  :+1: 

@ConvexPolygon Whoa!  Interesting!  Do you have any experience with Node?

**Comment by ConvexPolygon** [comment]
> @Skyclo Really appreciate it! I understand you're busy with Ideoxan, though. I'll be sure to let you know if I really need any major backend help. 👍
> 
> @ConvexPolygon Whoa! Interesting! Do you have any experience with Node?

A little. It should be enough. Node is Javascript-Based and adds in a package manager if I am correct. I could take the Node course.

**Comment by Nambaseking01** [comment]
Hey Convex

**Comment by Nambaseking01** [comment]
Get on Modchat lel

**Comment by Nambaseking01** [comment]
Its offline :(

**Comment by MossW268** [comment]
I'm willing to help! I'm learning node.js!

**Comment by micahlt** [comment]
@MossW268 Great!  

@ConvexPolygon Do you think we can come up with a solution to prevent users impersonating other users?

**Comment by ConvexPolygon** [comment]
@micahlt we're using SV, right? Just add a 'From *user* at *timestamp*'
Then we can easily know who is who.

**Comment by Skyclo** [comment]
> @micahlt we're using SV, right? Just add a 'From *user* at *timestamp*'
> Then we can easily know who is who.

Well that still doesn't fix the issue of impersonation. Even if we have logged information, damage can still be done between the time we recognize an impersonator. My suggestion would to have server side authentication. I haven't looked much into the Scratch API so I would need to do some research before assisting with this.

Also, I suggest we split up these into seperate issues so we can tackle them better

**Comment by Skyclo** [comment]
Is this being developed again?

**Comment by micahlt** [comment]
Yes, Modchat is back up and running.  I'm currently working on image
uploads!

**Comment by VelocityDesign** [comment]
YESSSSS! IT IS BACK!!!!!
