### ISSUE TITLE
[Bug] You can use HTML elements in your message

### ISSUE THREAD

**Issue by BoomerScratch** [micahlt/modchat#20]
**Describe the bug**
When you type in an HTML element, and press "send", it actually turns into an HTML element! This can be dangerous, like someone typing in `<style>html{display:none}</style>`, which will make the page blank.

**Expected behavior**
It doesn't happen.

**Screenshots**
![5765cf4a-3a3a-4f7b-a3c3-26ae6a42ff40](https://user-images.githubusercontent.com/60622217/84569308-d12f1200-ad85-11ea-99f7-cfdb01652af0.gif)

**Additional context**
This can be fixed by using innerText instead of innerHTML.

Browser and OS: Chrome 83.0.4103.97, Windows NT 10.0.

**Comment by micahlt** [comment]
@BoomerScratch Whoa!  I could have sworn I was already using innerText!  Thanks for the catch 😊

**Comment by BoomerScratch** [comment]
@micahlt 1760d15 fixed this bug, so I'm closing the issue.
