### ISSUE TITLE
[Bug] Commit 1760d15 broke mentioning...

### ISSUE THREAD

**Issue by BoomerScratch** [micahlt/modchat#21]
**Describe the bug**
1760d15 fixed #20, but it caused another bug. Now, mentioning broke.

**Expected behavior**
Mentioning works normally.

**Screenshots**
![](https://user-images.githubusercontent.com/60622217/84590983-237e3a80-ae3b-11ea-80e8-ccf57135ed82.png)

**Comment by qucchia** [comment]
This is fixed now with [a7d0304](https://github.com/micahlt/modchat/commit/a7d0304d784680814523fb661747e34fb31292ce).

**Comment by micahlt** [comment]
Thanks, @qucchia!  @BoomerScratch Yep, fixed!
