### ISSUE TITLE
[Bug] Hey I can't login.

### ISSUE THREAD

**Issue by Ani-Xan** [micahlt/modchat#28]
@micahlt 

**Describe the bug**
When I hit the purple button nothing seems to happen.

**Expected behavior**
I would think that it would redirect me to the verification page or something/ 

**Screenshots**
![Not Working Please Help](https://user-images.githubusercontent.com/57809064/99884575-25b3a480-2be4-11eb-8704-23cef9f5c1a9.gif)

**Additional context**
What's wrong? (Also, I have some extensions that say that they have permission to change the page.)

**Comment by Ani-Xan** [comment]
I have also tried disabling my extensions with no effect. And using a VPN in case a network was blocked. I am confused. @micahlt

**Comment by micahlt** [comment]
@Ani-Xan Ah!  What you have to do is copy the code and comment it on your Scratch profile.  Then click Verify!

**Comment by Ani-Xan** [comment]
@micahlt You should add a small bit of text under the code to let users know to do that. 😃
