### ISSUE TITLE
[Idea] Emojis between :colons:

### ISSUE THREAD

**Issue by qucchia** [micahlt/modchat#36]
**Is your feature request related to a problem? Please describe.**
It can be difficult for some people to insert emojis into their messages.

**Describe the solution you'd like**
For example, use [emoji-name-map](https://www.npmjs.com/package/emoji-name-map) to map words between colons to emojis: for example, `:grinning:` turns into 😀. We could also add custom emojis, even the Scratch ones!

**Comment by micahlt** [comment]
Added in 7a61e0366c2580b4b8da13cf0982b38e6881513f!
