### ISSUE TITLE
[Idea] </ breaks messages

### ISSUE THREAD

**Issue by VelocityDesign** [micahlt/modchat#38]
**Describe the bug**
Whenever a user messages </, it breaks the messages (See Screenshot)
**Expected behavior**
</ gets printed, etc. No bug.
**Screenshots**
![image](https://user-images.githubusercontent.com/24457862/100156020-da142b80-2e6d-11eb-8b92-8e5173c5c9c2.png)

**Additional context**
Add any other context about the problem here. This is optional.

**Comment by micahlt** [comment]
This is a security feature to prevent users from embedding HTML or JavaScript within messages.  However, a UI fix is needed.

**Comment by micahlt** [comment]
@VelocityDesign  this was fixed in 90a10da1220ee1d5ffcfcd6d370985a8e9eeeb8b
