### ISSUE TITLE
What.

### ISSUE THREAD

**Issue by sargent-coding** [micahlt/modchat#41]
![image](https://user-images.githubusercontent.com/65425469/101246082-f5d5c800-36de-11eb-8425-4fd2e817ef55.png)

**Comment by AmazingMech2418** [comment]
We were working on fixing vulnerabilities. IDK why it said October 19th though. XD

**Comment by micahlt** [comment]
@sargent-coding Please ensure that if you're filing an issue, you include more context.  This applies to all of GitHub 😃
