### ISSUE TITLE
I was banned, how am I supposed to complete verification?

### ISSUE THREAD

**Issue by MTM828** [micahlt/modchat#51]
LOL, I was banned on there, how am I supposed to log in??
Don't ask me why, everyone knows how annoyingly strict the Scratch Team is. 😒

**Comment by micahlt** [comment]
@MTM828 The issue is, adding other methods of authentication is  complicated and well out of the scope of Modchat.  Unfortunately, development on it has stopped as well.

**Comment by MTM828** [comment]
> @MTM828 The issue is, adding other methods of authentication is complicated and well out of the scope of Modchat. Unfortunately, development on it has stopped as well.

:/
