### ISSUE TITLE
[Bug] Moderators are banning me for no reason

### ISSUE THREAD

**Issue by YodaLightsabr** [micahlt/modchat#59]
People keep banning me; and there's no explanation.

**Comment by YodaLightsabr** [comment]
Sorry if this doesn't belong in the issues, but it kind of is an issue. If I really should be banned, then add a feature to tell the banned person why. I got banned 3 times on 3 different accounts because an unknown person keeps banning me.

**Comment by micahlt** [comment]
Modchat is no longer being maintained, and the Heroku server is shutting down soon.
