### ISSUE TITLE
[Transition] [Waiting for release] Switch to SOA2

### ISSUE THREAD

**Issue by Semisol** [micahlt/modchat#62]
**Is your feature request related to a problem? Please describe.**
Switching from SV to SOA2.

**Describe the solution you'd like**
A few API changes, login will be moved over to a website redirect.

**Describe alternatives you've considered**
None

**Additional context**
Deprecation of SV to be replaced by SOA2, currently WIP
Expected to be out in 15 days or so

**Comment by micahlt** [comment]
@Semisol so 15 days was a pretty long time ago - what's the status of SOA2?

**Comment by Semisol** [comment]
> @Semisol so 15 days was a pretty long time ago - what's the status of SOA2?

Almost out
We are currently sorting out hosting (Scratch Wiki/Self Hosted) and testing.

**Comment by micahlt** [comment]
All righty - just let me know when it's done!

**Comment by YodaLightsabr** [comment]
See #70 for alternatives

**Comment by micahlt** [comment]
@Semisol any updates on this?

**Comment by Semisol** [comment]
> @Semisol any updates on this?

There was a bug left unfixed for a few months so I have contacted Ken about the issue.

**Comment by Semisol** [comment]
I am ready to open the service in a few days if the bug get patched.

**Comment by micahlt** [comment]
@Semisol All righty!  I'm curious - what's the bug?

**Comment by Semisol** [comment]
> @Semisol All righty! I'm curious - what's the bug?

Infinite login loop, something in the code verification is failing.

**Comment by micahlt** [comment]
> Infinite login loop

Ah, fun.  There's not a huge hurry on Modchat's end right now - I'm looking forward to release 😄

**Comment by Semisol** [comment]
> > Infinite login loop
> 
> Ah, fun. There's not a huge hurry on Modchat's end right now - I'm looking forward to release 😄

There is no error message which makes it more confusing

**Comment by micahlt** [comment]
Oh, that is odd!  Huh.

**Comment by Semisol** [comment]
> Oh, that is odd! Huh.

nvm. Ken redirected to the start if the login was done without a redirect_url sooo

**Comment by Semisol** [comment]
almost ready to release, docs already are HOPEFULLY done
gonna do a test then we will release

**Comment by Semisol** [comment]
Closing due to new work on V2 and that the code would be obsoleted soon.
