### ISSUE TITLE
[Bug] I can kill Modchat with a single line of code

### ISSUE THREAD

**Issue by YodaLightsabr** [micahlt/modchat#64]
**Describe the bug**
```js
socket.emit('ban');
```
**Expected behavior**
Modchat doesn't crash

**Screenshots**
![image](https://user-images.githubusercontent.com/76178582/108645044-40591c00-7466-11eb-885f-de5e7fcc3966.png)

**Comment by YodaLightsabr** [comment]
![image](https://user-images.githubusercontent.com/76178582/108645135-a8a7fd80-7466-11eb-9e82-cc85f5d10b9f.png)

**Comment by micahlt** [comment]
Looks like there just needs to be an authentication handler - would you be willing to look into it?

**Comment by AmazingMech2418** [comment]
@micahlt We had the same issues over on ScratchChat before. Just add a filter to check to make sure the parameters aren't undefined or null.

**Comment by YodaLightsabr** [comment]
> @micahlt We had the same issues over on ScratchChat before. Just add a filter to check to make sure the parameters aren't undefined or null.

Yeah I fixed it before on BluChat.

**Comment by micahlt** [comment]
This has already been fixed in b1c38e7bb3631b961a7128069586a00281fd49fc.
