### ISSUE TITLE
[Bug] Verification Codes unintentionally contain swear words

### ISSUE THREAD

**Issue by DewMcStew** [micahlt/modchat#69]
It appears that verification codes don't have any kind of filter, and I got muted on Scratch while trying to post one.

Maybe a filter of sorts could be added?

**Comment by Semisol** [comment]
dead issue?
@micahlt close when auth is reimplemented

**Comment by micahlt** [comment]
@Semisol @DewMcStew This has been fixed!

**Comment by Semisol** [comment]
> @Semisol @DewMcStew This has been fixed!

Ok, but where?

**Comment by micahlt** [comment]
> > @Semisol @DewMcStew This has been fixed!
> 
> Ok, but where?

Oh, whoops - just realized I haven't pushed it to GitHub yet.  I'll do that now.
