### ISSUE TITLE
[Idea] Smileys should be a thing

### ISSUE THREAD

**Issue by Nambaseking01** [micahlt/modchat#7]
**Describe the solution you'd like**
Basically, I'd like smileys to be integrated into this chat. For example, there'd be a smileys section. There could be a little smiley emoticon next to the typing section like infamous social media, and when you click on it you see a vast section of smileys. You could also use shortcuts like ":D" or ":)" to make it easier.

**Describe alternatives you've considered**
I'm pretty sure there's an API for this - searched it up on Google but couldn't find any. Maybe you know some? Also, maybe someone could make a mockup for this? Thanks!

**Comment by micahlt** [comment]
@Nambaseking01 Modchat already supports emoji.  If you're on Windows, type `Win+Period` to access them and if you're on Linux you can copy and paste.
